hifis-net/ansible-role-gitlab-runner

.github/workflows/ci.yml
- fixes #6 
- Runs at `00:00UTC` every day
=> fixes(#6): CI daily run

CHANGELOG.md, CHANGELOG.md.license, HISTORY.md, HISTORY.md.license, VERSION
=> Release version 0.6.0

defaults/main.yml
* [Release Notes](https://github.com/flatcar-linux/container-linux-config-transpiler/releases/tag/v0.9.3)
* [Commits](https://github.com/flatcar-linux/container-linux-config-transpiler/compare/v0.9.2...v0.9.3)
=> Install container-linux-config-transpiler v0.9.3

.github/workflows/ci.yml, meta/main.yml
=> Add support for Debian 11

defaults/main.yml, molecule/default/molecule.yml, molecule/default/verify.yml, tasks/update-configuration.yml
This allows us to get monitoring information via Prometheus.
=> Allow to configure the listen_address

README.md, molecule/default/molecule.yml, tasks/register.yml, tasks/update-runner-configuration.yml
=> Allow to configure docker devices and security_opts

README.md, molecule/default/molecule.yml, tasks/register.yml, tasks/update-runner-configuration.yml
=> Allow to configure cpus, memory and gpus

molecule/default/molecule.yml, molecule/default/prepare.yml, tasks/configuration.yml, tasks/install.debianlike.yml, tasks/main.yml, tasks/update-configuration.yml, tasks/update-runner-configuration.yml
=> feat: add initial dry-run support

CITATION.cff
=> chore: add CITATION.cff

.github/workflows/ci.yml, meta/main.yml
=> chore!: drop official support for Ubuntu 18.04

.github/workflows/ci.yml, README.md, meta/main.yml, molecule/default/molecule.yml
=> feat: add support for Debian 12

meta/main.yml
=> chore: set minimum ansible version to 2.13

README.md, defaults/main.yml, molecule/default/molecule.yml, tasks/update-configuration.yml
=> feat: enable session_server configuration

README.md, molecule/default/molecule.yml, tasks/register.yml, tasks/update-runner-configuration.yml
=> feat: allow to disable local docker cache

defaults/main.yml, templates/flatcar-linux-config.bu.j2
=> Make Flatcar configuration compatible with most recent release

README.md, defaults/main.yml, molecule/default/molecule.yml, templates/flatcar-linux-config.bu.j2
=> feat: configure insecure registries in Flatcar config

README.md, molecule/default/molecule.yml, tasks/update-runner-configuration.yml
See https://docs.gitlab.com/runner/executors/docker.html#overriding-the-mtu-of-the-created-network
Closes #205
=> feat: allow to configure network_mtu parameter

tasks/install.debianlike.yml
=> feat: allow to downgrade gitlab-runner package

README.md, defaults/main.yml, molecule/default/molecule.yml, templates/config.toml.j2
=> feat: allow to configure the sentry_dsn parameter

.github/workflows/prepare-action/action.yml, poetry.lock, pyproject.toml
* Minimum Python 3.11
* Use Python 3.12 in Actions
* Use most recent setup-python action
* Update Python dependencies
=> Update all dependencies

.github/workflows/ci.yml, meta/main.yml, molecule/default/molecule.yml
=> Add support for Ubuntu 24.04

.github/workflows/ci.yml
Try to rely on the built-in Podman version.
=> Use Ubuntu 24.04 in GitHub Actions
